#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
validator="$repo_root/Scripts/validate-package.sh"
work_dir="$(mktemp -d /tmp/pomme-packaging-identity.XXXXXX)"
trap 'rm -rf "$work_dir"' EXIT

payload="$work_dir/payload"
mkdir -p "$payload/usr/local/bin"
printf '#!/bin/sh\nexit 0\n' > "$payload/usr/local/bin/pomme"
chmod 0755 "$payload/usr/local/bin/pomme"

run_validator() {
  bash "$validator" \
    --payload-root "$payload" \
    --entitlements "$repo_root/Config/pomme.entitlements" \
    "$@"
}

run_validator

# Exercise the actual archive listing, including pkgbuild's parent directories
# and any AppleDouble metadata generated by the host filesystem.
pkgbuild --root "$payload" --identifier com.github.weswhet.pomme.test \
  --version 1 --install-location / "$work_dir/pomme.pkg" >/dev/null
run_validator --pkg "$work_dir/pomme.pkg"

# Keep the staged root valid so this rejection comes from archive inspection.
foreign_payload="$work_dir/foreign-payload"
cp -R "$payload" "$foreign_payload"
printf 'foreign\n' > "$foreign_payload/usr/local/bin/foreign-cli"
pkgbuild --root "$foreign_payload" --identifier com.github.weswhet.pomme.test \
  --version 1 --install-location / "$work_dir/foreign.pkg" >/dev/null
if run_validator --pkg "$work_dir/foreign.pkg" >"$work_dir/foreign-pkg.log" 2>&1; then
  echo "validator accepted a foreign pkg payload file" >&2
  exit 1
fi
grep -q 'unexpected pkg payload' "$work_dir/foreign-pkg.log"

# Deterministic listings cover metadata even on hosts without extended attrs.
mock_bin="$work_dir/mock-bin"
mkdir -p "$mock_bin"
printf '#!/bin/sh\ncat "$POMME_TEST_PKG_LISTING"\n' > "$mock_bin/pkgutil"
chmod 0755 "$mock_bin/pkgutil"
listing="$work_dir/pkg-listing"
printf '%s\n' . ./usr/ ./usr/local/ ./usr/local/bin/ \
  ./._usr ./usr/._local ./usr/local/._bin ./usr/local/bin/._pomme \
  ./usr/local/bin/pomme > "$listing"
PATH="$mock_bin:$PATH" POMME_TEST_PKG_LISTING="$listing" \
  run_validator --pkg "$work_dir/pomme.pkg"
printf '%s\n' ./usr/local/bin/._foreign-cli >> "$listing"
if PATH="$mock_bin:$PATH" POMME_TEST_PKG_LISTING="$listing" \
  run_validator --pkg "$work_dir/pomme.pkg" >"$work_dir/metadata.log" 2>&1; then
  echo "validator accepted foreign pkg metadata" >&2
  exit 1
fi
grep -q 'unexpected pkg payload metadata' "$work_dir/metadata.log"
printf '%s\n' . ./usr/local/bin/._pomme > "$listing"
if PATH="$mock_bin:$PATH" POMME_TEST_PKG_LISTING="$listing" \
  run_validator --pkg "$work_dir/pomme.pkg" >"$work_dir/missing.log" 2>&1; then
  echo "validator accepted metadata without the pkg executable" >&2
  exit 1
fi
grep -q 'pkg payload does not contain' "$work_dir/missing.log"

# Any foreign executable or guest path in the host package is a hard failure.
printf '#!/bin/sh\nexit 0\n' > "$payload/usr/local/bin/foreign-cli"
chmod 0755 "$payload/usr/local/bin/foreign-cli"
if run_validator >/dev/null 2>&1; then
  echo "validator accepted a foreign host executable" >&2
  exit 1
fi
rm -f "$payload/usr/local/bin/foreign-cli"

mkdir -p "$payload/usr/local/libexec"
if run_validator >/dev/null 2>&1; then
  echo "validator accepted a guest directory in the host package" >&2
  exit 1
fi
rmdir "$payload/usr/local/libexec"

mkdir -p "$payload/usr/local/libexec"
printf '#!/bin/sh\nexit 0\n' > "$payload/usr/local/libexec/pomme"
chmod 0755 "$payload/usr/local/libexec/pomme"
if run_validator >/dev/null 2>&1; then
  echo "validator accepted a guest service in the host package" >&2
  exit 1
fi
rm -f "$payload/usr/local/libexec/pomme"
rmdir "$payload/usr/local/libexec"

tar_root="$work_dir/tar-root"
mkdir -p "$tar_root"
cp "$payload/usr/local/bin/pomme" "$tar_root/pomme"
tar -C "$tar_root" -czf "$work_dir/pomme.tar.gz" pomme
run_validator --tarball "$work_dir/pomme.tar.gz"

printf 'foreign\n' > "$tar_root/foreign-cli"
tar -C "$tar_root" -czf "$work_dir/foreign.tar.gz" pomme foreign-cli
if run_validator --tarball "$work_dir/foreign.tar.gz" >/dev/null 2>&1; then
  echo "validator accepted a foreign tarball entry" >&2
  exit 1
fi

bad_entitlements="$work_dir/bad.entitlements"
sed 's/<true\/>/<false\/>/' \
  "$repo_root/Config/pomme.entitlements" > "$bad_entitlements"
if bash "$validator" --payload-root "$payload" --entitlements "$bad_entitlements" >/dev/null 2>&1; then
  echo "validator accepted a package without Virtualization entitlement" >&2
  exit 1
fi

echo "Packaging identity checks passed."
